### ISSUE TITLE
Redundant code line

### ISSUE THREAD

**Issue by NikBelyaev** [LikaloLLC/docsie-universal-doc-importer#23]
https://github.com/LikaloLLC/docsie-universal-doc-importer/blob/89dae7a55e0ae74ced4e8f72fd7eaf2b5b26d0dd/universal_doc_importer/views.py#L23

I think it can be removed.

**Comment by Zarif99** [comment]
if i remove this line it returns error like [this](https://dpaste.com/H653XCH87)

**Comment by NikBelyaev** [comment]
Try to add `self.load()` in the `def by_id(...)` then.
https://github.com/LikaloLLC/docsie-universal-doc-importer/blob/89dae7a55e0ae74ced4e8f72fd7eaf2b5b26d0dd/universal_doc_importer/registry.py#L5-L10
